package mx.unam.ciencias.is.modelo;
// Generated 20/02/2018 02:12:22 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ExperienciaLaboralId generated by hbm2java
 */
public class ExperienciaLaboralId  implements java.io.Serializable {


     private int idProfesionista;
     private String empresa;
     private String cargo;
     private Date inicioPeriodo;
     private Date finPeriodo;

    public ExperienciaLaboralId() {
    }

    public ExperienciaLaboralId(int idProfesionista, String empresa, String cargo, Date inicioPeriodo, Date finPeriodo) {
       this.idProfesionista = idProfesionista;
       this.empresa = empresa;
       this.cargo = cargo;
       this.inicioPeriodo = inicioPeriodo;
       this.finPeriodo = finPeriodo;
    }
   
    public int getIdProfesionista() {
        return this.idProfesionista;
    }
    
    public void setIdProfesionista(int idProfesionista) {
        this.idProfesionista = idProfesionista;
    }
    public String getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public Date getInicioPeriodo() {
        return this.inicioPeriodo;
    }
    
    public void setInicioPeriodo(Date inicioPeriodo) {
        this.inicioPeriodo = inicioPeriodo;
    }
    public Date getFinPeriodo() {
        return this.finPeriodo;
    }
    
    public void setFinPeriodo(Date finPeriodo) {
        this.finPeriodo = finPeriodo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ExperienciaLaboralId) ) return false;
		 ExperienciaLaboralId castOther = ( ExperienciaLaboralId ) other; 
         
		 return (this.getIdProfesionista()==castOther.getIdProfesionista())
 && ( (this.getEmpresa()==castOther.getEmpresa()) || ( this.getEmpresa()!=null && castOther.getEmpresa()!=null && this.getEmpresa().equals(castOther.getEmpresa()) ) )
 && ( (this.getCargo()==castOther.getCargo()) || ( this.getCargo()!=null && castOther.getCargo()!=null && this.getCargo().equals(castOther.getCargo()) ) )
 && ( (this.getInicioPeriodo()==castOther.getInicioPeriodo()) || ( this.getInicioPeriodo()!=null && castOther.getInicioPeriodo()!=null && this.getInicioPeriodo().equals(castOther.getInicioPeriodo()) ) )
 && ( (this.getFinPeriodo()==castOther.getFinPeriodo()) || ( this.getFinPeriodo()!=null && castOther.getFinPeriodo()!=null && this.getFinPeriodo().equals(castOther.getFinPeriodo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdProfesionista();
         result = 37 * result + ( getEmpresa() == null ? 0 : this.getEmpresa().hashCode() );
         result = 37 * result + ( getCargo() == null ? 0 : this.getCargo().hashCode() );
         result = 37 * result + ( getInicioPeriodo() == null ? 0 : this.getInicioPeriodo().hashCode() );
         result = 37 * result + ( getFinPeriodo() == null ? 0 : this.getFinPeriodo().hashCode() );
         return result;
   }   


}


