package mx.unam.ciencias.is.modelo;
// Generated 20/02/2018 02:12:22 PM by Hibernate Tools 4.3.1



/**
 * ExperienciaLaboral generated by hbm2java
 */
public class ExperienciaLaboral  implements java.io.Serializable {


     private ExperienciaLaboralId id;
     private Profesionista profesionista;

    public ExperienciaLaboral() {
    }

    public ExperienciaLaboral(ExperienciaLaboralId id, Profesionista profesionista) {
       this.id = id;
       this.profesionista = profesionista;
    }
   
    public ExperienciaLaboralId getId() {
        return this.id;
    }
    
    public void setId(ExperienciaLaboralId id) {
        this.id = id;
    }
    public Profesionista getProfesionista() {
        return this.profesionista;
    }
    
    public void setProfesionista(Profesionista profesionista) {
        this.profesionista = profesionista;
    }




}


