package mx.unam.ciencias.is.modelo;
// Generated 20/02/2018 02:12:22 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * FormacionAcademicaId generated by hbm2java
 */
public class FormacionAcademicaId  implements java.io.Serializable {


     private int idProfesionista;
     private String colegio;
     private String grado;
     private Date inicioPeriodo;
     private Date finPeriodo;

    public FormacionAcademicaId() {
    }

    public FormacionAcademicaId(int idProfesionista, String colegio, String grado, Date inicioPeriodo, Date finPeriodo) {
       this.idProfesionista = idProfesionista;
       this.colegio = colegio;
       this.grado = grado;
       this.inicioPeriodo = inicioPeriodo;
       this.finPeriodo = finPeriodo;
    }
   
    public int getIdProfesionista() {
        return this.idProfesionista;
    }
    
    public void setIdProfesionista(int idProfesionista) {
        this.idProfesionista = idProfesionista;
    }
    public String getColegio() {
        return this.colegio;
    }
    
    public void setColegio(String colegio) {
        this.colegio = colegio;
    }
    public String getGrado() {
        return this.grado;
    }
    
    public void setGrado(String grado) {
        this.grado = grado;
    }
    public Date getInicioPeriodo() {
        return this.inicioPeriodo;
    }
    
    public void setInicioPeriodo(Date inicioPeriodo) {
        this.inicioPeriodo = inicioPeriodo;
    }
    public Date getFinPeriodo() {
        return this.finPeriodo;
    }
    
    public void setFinPeriodo(Date finPeriodo) {
        this.finPeriodo = finPeriodo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FormacionAcademicaId) ) return false;
		 FormacionAcademicaId castOther = ( FormacionAcademicaId ) other; 
         
		 return (this.getIdProfesionista()==castOther.getIdProfesionista())
 && ( (this.getColegio()==castOther.getColegio()) || ( this.getColegio()!=null && castOther.getColegio()!=null && this.getColegio().equals(castOther.getColegio()) ) )
 && ( (this.getGrado()==castOther.getGrado()) || ( this.getGrado()!=null && castOther.getGrado()!=null && this.getGrado().equals(castOther.getGrado()) ) )
 && ( (this.getInicioPeriodo()==castOther.getInicioPeriodo()) || ( this.getInicioPeriodo()!=null && castOther.getInicioPeriodo()!=null && this.getInicioPeriodo().equals(castOther.getInicioPeriodo()) ) )
 && ( (this.getFinPeriodo()==castOther.getFinPeriodo()) || ( this.getFinPeriodo()!=null && castOther.getFinPeriodo()!=null && this.getFinPeriodo().equals(castOther.getFinPeriodo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdProfesionista();
         result = 37 * result + ( getColegio() == null ? 0 : this.getColegio().hashCode() );
         result = 37 * result + ( getGrado() == null ? 0 : this.getGrado().hashCode() );
         result = 37 * result + ( getInicioPeriodo() == null ? 0 : this.getInicioPeriodo().hashCode() );
         result = 37 * result + ( getFinPeriodo() == null ? 0 : this.getFinPeriodo().hashCode() );
         return result;
   }   


}


