package mx.unam.ciencias.is.modelo;
// Generated 20/02/2018 02:12:22 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Profesionista generated by hbm2java
 */
public class Profesionista  implements java.io.Serializable {


     private int idProfesionista;
     private String carrera;
     private String nacionalidad;
     private String contrasena;
     private String telefono;
     private String correo;
     private String nombre;
     private Set formacionAcademicas = new HashSet(0);
     private Set vacantes = new HashSet(0);
     private Set skillses = new HashSet(0);
     private Set experienciaLaborals = new HashSet(0);

    public Profesionista() {
    }

	
    public Profesionista(int idProfesionista, String carrera, String nacionalidad, String contrasena, String nombre) {
        this.idProfesionista = idProfesionista;
        this.carrera = carrera;
        this.nacionalidad = nacionalidad;
        this.contrasena = contrasena;
        this.nombre = nombre;
    }
    public Profesionista(int idProfesionista, String carrera, String nacionalidad, String contrasena, String telefono, String correo, String nombre, Set formacionAcademicas, Set vacantes, Set skillses, Set experienciaLaborals) {
       this.idProfesionista = idProfesionista;
       this.carrera = carrera;
       this.nacionalidad = nacionalidad;
       this.contrasena = contrasena;
       this.telefono = telefono;
       this.correo = correo;
       this.nombre = nombre;
       this.formacionAcademicas = formacionAcademicas;
       this.vacantes = vacantes;
       this.skillses = skillses;
       this.experienciaLaborals = experienciaLaborals;
    }
   
    public int getIdProfesionista() {
        return this.idProfesionista;
    }
    
    public void setIdProfesionista(int idProfesionista) {
        this.idProfesionista = idProfesionista;
    }
    public String getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(String carrera) {
        this.carrera = carrera;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getFormacionAcademicas() {
        return this.formacionAcademicas;
    }
    
    public void setFormacionAcademicas(Set formacionAcademicas) {
        this.formacionAcademicas = formacionAcademicas;
    }
    public Set getVacantes() {
        return this.vacantes;
    }
    
    public void setVacantes(Set vacantes) {
        this.vacantes = vacantes;
    }
    public Set getSkillses() {
        return this.skillses;
    }
    
    public void setSkillses(Set skillses) {
        this.skillses = skillses;
    }
    public Set getExperienciaLaborals() {
        return this.experienciaLaborals;
    }
    
    public void setExperienciaLaborals(Set experienciaLaborals) {
        this.experienciaLaborals = experienciaLaborals;
    }




}


